In [1]:
1+1

2

In [2]:
## Numpy
import numpy as np

In [4]:
lst=[1,2,3,4]
arr=np.array(lst)

In [14]:
arr

array([1, 2, 3, 4])

In [6]:
type(arr)

numpy.ndarray

In [7]:
arr.shape

(4,)

In [9]:
arr1=np.array([[1,2,3],[4,5,6]])

In [11]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
## 2 dimension 
arr1.shape

(2, 3)

In [13]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [15]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [16]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [17]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
arr1.dtype

dtype('int32')

In [27]:
np.arange(1,20,2).reshape(2,5).shape

(2, 5)

In [30]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [31]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [34]:
np.linspace(1,20,40).reshape(20,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [36]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [40]:
np.ones((5,2,8))

array([[[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1.]]])

In [42]:
5 + np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [45]:
np.eye(6).reshape(12,3)

array([[1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 0., 0.],
       [0., 1., 0.],
       [0., 0., 0.],
       [0., 0., 1.]])

In [46]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [47]:
print("Random number generation(Uniform distribution)")
np.random.rand(2,3)

Random number generation(Uniform distribution)


array([[0.27648494, 0.47760847, 0.84575455],
       [0.74114308, 0.86762982, 0.74519907]])

In [48]:
print("Random number following a Normal distribtuion with mean=0 and std=1")
print(np.random.randn(5,3))

Random number following a Normal distribtuion with mean=0 and std=1
[[-0.9340845   0.4016104  -1.25289848]
 [ 0.52970024 -0.70942567 -1.55734796]
 [ 1.46974406  0.1388035  -0.09355534]
 [ 0.26396623  1.98810795  0.46080921]
 [-0.62569981  1.47247936  0.19291716]]


In [61]:
np.random.randint(1,100,50)

array([22, 65, 99, 59,  1, 34, 17,  6, 56, 42,  2, 73, 16,  9, 21, 84, 61,
       77,  3, 46, 35, 24, 85, 42, 70, 57,  1, 80, 66, 71,  4, 64, 48, 57,
        7, 88,  1, 97, 22, 70, 69,  9, 56, 61, 62, 43, 85, 67, 98, 68])

In [62]:
np.random.randint(1,100,(4,4))

array([[30, 11, 87, 46],
       [98, 78, 20, 96],
       [98, 85, 26,  7],
       [57, 15, 52, 93]])

In [64]:
arr=np.arange(0,11)

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [76]:
## Slicing

arr[2:7:3]

array([2, 5])

In [73]:
arr[-1:7:-1]

array([10,  9,  8])

In [80]:
arr[-1:3:-1]

array([10,  9,  8,  7,  6,  5,  4])

In [83]:
arr1=np.random.randint(2,100,20).reshape(5,4)

In [84]:
arr1

array([[71, 78, 94, 67],
       [43, 61, 18, 71],
       [48, 31, 28, 87],
       [53, 30, 40, 34],
       [68, 74, 90, 59]])

In [89]:
arr1[3:,1:]

array([[30, 40, 34],
       [74, 90, 59]])

In [87]:
arr1[0:3,0:3]

array([[71, 78, 94],
       [43, 61, 18],
       [48, 31, 28]])

In [98]:
arr1[-3:-1,-3:-1]



array([[31, 28],
       [30, 40]])

In [114]:
## universal functions

arr1=np.random.randint(1,100,(3,3))
arr2=np.random.randint(20,100,(3,3))

In [100]:
arr1

array([[82, 96, 60],
       [55, 34, 53],
       [95, 33, 75]])

In [101]:
arr2

array([[76, 26, 66],
       [36, 45, 81],
       [27, 34, 97]])

In [102]:
arr1 + arr2

array([[158, 122, 126],
       [ 91,  79, 134],
       [122,  67, 172]])

In [103]:
arr1 * arr2

array([[6232, 2496, 3960],
       [1980, 1530, 4293],
       [2565, 1122, 7275]])

In [104]:
arr1 / arr2

array([[1.07894737, 3.69230769, 0.90909091],
       [1.52777778, 0.75555556, 0.65432099],
       [3.51851852, 0.97058824, 0.77319588]])

In [105]:
np.sqrt(arr1)

array([[9.05538514, 9.79795897, 7.74596669],
       [7.41619849, 5.83095189, 7.28010989],
       [9.74679434, 5.74456265, 8.66025404]])

In [106]:
np.exp(arr2)

array([[1.01480039e+33, 1.95729609e+11, 4.60718663e+28],
       [4.31123155e+15, 3.49342711e+19, 1.50609731e+35],
       [5.32048241e+11, 5.83461743e+14, 1.33833472e+42]])

In [107]:
np.log10(arr1)

array([[1.91381385, 1.98227123, 1.77815125],
       [1.74036269, 1.53147892, 1.72427587],
       [1.97772361, 1.51851394, 1.87506126]])

In [109]:
arr1=np.arange(1,10)

In [111]:
arr1[2:]=1000

In [112]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [115]:
np.dot(arr1,arr2)

array([[ 2678,  5044,  4277],
       [ 6942, 13006, 10802],
       [ 3754,  7332,  5991]])

In [116]:
np.matmul(arr1,arr2)

array([[ 2678,  5044,  4277],
       [ 6942, 13006, 10802],
       [ 3754,  7332,  5991]])